model_name: [["facebook/deit-tiny-patch16-224"], ["microsoft/swin-large-patch4-window12-384"], ["google/vit-base-patch16-384"]]
dataset_name: [["imagenet-1k"]]
dataset_split: [["validation"]]
metric: [["renggli"], ["parc"]]
n_samples: [[250, 500, 1000, 2500, 5000, 10000, 25000]]
random_states:  [[42, 43, 45]]
feat_red_dims: [[16, 32, 64, 127, 256, 512]]
