# Where to save results
save_dir: results_pets

# HuggingFace model names or paths to local models to compute metrics for
model_name:
  - facebook/deit-tiny-patch16-224

# HuggingFace Datasets or paths to datasets to compute metrics for
dataset_name:
  - "pcuenq/oxford-pets"

# Name of dataset split to compute metrics for (Currently must be the same for all datasets)
dataset_split:
  - "train"

# Metrics to compute
metrics:
  - "renggli"

# No. of images to compute the metrics with
n_samples:
  - 500

# Random seeds to use (e.g. for sampling the images to use)
random_state:
  - 42
