# Where to save results
save_dir: results_wp1

# HuggingFace model names or paths to local models to compute metrics for
model_name:
  - facebook/deit-tiny-patch16-224
  - facebook/deit-small-patch16-224
  - facebook/deit-base-patch16-224
  - microsoft/cvt-13
  - google/vit-base-patch16-384

# HuggingFace Datasets or paths to datasets to compute metrics for
dataset_name:
  - "imagenet-1k"

# Name of dataset split to compute metrics for (Currently must be the same for all datasets)
dataset_split:
  - "validation"

# Metrics to compute
metric:
  - "renggli"
  - "parc"

# No. of images to compute the metrics with
n_samples:
  - 500
  - 1000
  - 2000
  - 4000
  - 6000
  - 8000
  - 10000
  - 12000
  - 14000
  - 16000

# Random seeds to use (e.g. for sampling the images to use)
random_state:
  - 42
  - 43
  - 44
