caches:
  datasets: null
  models: null
dataset_name: pcuenq/oxford-pets
dataset_split: train
dataset_args:
  train_split: train
  val_split: validation
  test_split: test
  val_size: 0.15
  test_size: 0.15
  keep_labels: null
  keep_size: null
local_save: True
metrics:
- renggli
- n_pars
- LogME
metric_kwargs: null
model_name: facebook/deit-tiny-patch16-224
n_samples: 500
random_state: 42
save_dir: results/pets
