Intel/vit-base-patch16-224-int8-static: 80.576
apple/mobilevit-small: 78.4
apple/mobilevit-xx-small: 69.0
facebook/deit-base-patch16-224: 81.8
facebook/deit-base-patch16-384: 82.9
facebook/deit-small-patch16-224: 79.9
facebook/deit-tiny-patch16-224: 72.2
facebook/dinov2-base-imagenet1k-1-layer: 84.5
facebook/dinov2-small-imagenet1k-1-layer: 81.1
google/vit-base-patch16-384: 85.49
google/vit-large-patch16-224: 87.76
microsoft/beit-base-patch16-224: 83.2
microsoft/beit-base-patch16-224-pt22k-ft22k: 88.6
microsoft/beit-large-patch16-512: 88.6
microsoft/cvt-13: 81.6
microsoft/cvt-21-384-22k: 84.9
microsoft/swin-base-patch4-window12-384: 87.3
microsoft/swin-large-patch4-window12-384-in22k: 87.3
microsoft/swinv2-base-patch4-window8-256: 84.0
