apple/mobilevit-xx-small: 69.0
apple/mobilevit-small: 78.4
facebook/deit-tiny-patch16-224: 72.2
facebook/deit-small-patch16-224: 79.9
facebook/deit-base-patch16-224: 81.8
facebook/deit-base-patch16-384: 82.9
facebook/dinov2-small-imagenet1k-1-layer: 81.1
facebook/dinov2-base-imagenet1k-1-layer: 84.5
google/vit-base-patch16-384: 85.49
google/vit-large-patch16-224: 83.98
microsoft/beit-base-patch16-224: 85.2
microsoft/beit-base-patch16-384: 86.8
microsoft/beit-large-patch16-512: 88.6
microsoft/cvt-13: 81.6
microsoft/cvt-21-384: 83.3
microsoft/swin-base-patch4-window12-384: 86.4
microsoft/swin-large-patch4-window12-384-in22k: 87.3
microsoft/swinv2-base-patch4-window8-256: 84.2
microsoft/swinv2-large-patch4-window12to16-192to256-22kto1k-ft: 86.9
Zetatech/pvt-large-224: 81.7
facebook/deit-tiny-distilled-patch16-224: 74.5
facebook/deit-small-distilled-patch16-224: 81.2
facebook/deit-base-distilled-patch16-224: 83.4
facebook/deit-base-distilled-patch16-384: 85.2
timm/eva_giant_patch14_336.clip_ft_in1k: 89.466
timm/eva02_large_patch14_448.mim_m38m_ft_in22k_in1k: 90.054
facebook/levit-128S: 76.6
shi-labs/dinat-large-11x11-in22k-in1k-384: 87.5
